baseurl = "www.zainando.com"
languageCode = "it-it"
theme = "hugo_theme_robust"
title = "Zainando"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Chi siamo"
url = "/page/about/"
weight = 1
[[menu.social]]
identifier = "instagram"
name = "@zainandoperilmondo"
pre = "<i class='fa fa-instagram'></i>"
url = "https://instagram.com/zainandoperilmondo/"
weight = 1
[[menu.social]]
identifier = "facebook"
name = "@zainandoperilmondo"
pre = "<i class='fa fa-facebook'></i>"
url = "https://www.facebook.com/zainandoperilmondo/"
weight = 2
[outputs]
page = ["HTML", "AMP"]
[params]
GoogleAnalyticsUserID = "UA-97568677-1"
disqusShortname = "zainando"
[taxonomies]
category = "categories"
serie = "series"
tag = "tags"
